// <auto-generated />
using System;
using Example.SqlServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Example.SqlServer.Migrations.User;

[DbContext(typeof(MyDbContext))]
partial class MyDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Common.Entities.User", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasColumnName("created_at");

                b.Property<long>("CreatorId")
                    .HasColumnType("bigint")
                    .HasColumnName("creator_id");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit")
                    .HasColumnName("is_active");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit")
                    .HasColumnName("is_deleted");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)")
                    .HasColumnName("password_hash");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2")
                    .HasColumnName("updated_at");

                b.Property<long?>("UpdaterId")
                    .HasColumnType("bigint")
                    .HasColumnName("updater_id");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)")
                    .HasColumnName("username");

                b.HasKey("Id");

                b.ToTable("user");
            });
#pragma warning restore 612, 618
    }
}
